// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBrickVault.Infrastructure.Data;

#nullable disable

namespace TheBrickVault.Migrations
{
    [DbContext(typeof(LegoDbContext))]
    [Migration("20250304235056_SeedLegoSets")]
    partial class SeedLegoSets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("TheBrickVault.Core.Models.LegoSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Images")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Instructions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PartsList")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PieceCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetNum")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LegoSets");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Name = "Test Set",
                            SetNum = "123"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Another Test Set",
                            SetNum = "5678"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Yet Another Test Set",
                            SetNum = "91011593598"
                        },
                        new
                        {
                            Id = 9,
                            Name = "",
                            SetNum = "1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
